- name: Install helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

- name: Download kubectl
  shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

- name: Install kubectl
  shell: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: Install kubernetes package for pip
  pip:
    name: kubernetes
