---
- name: Add jenkins helm repo
  kubernetes.core.helm_repository:
    name: jenkins
    repo_url: "https://charts.jenkins.io"

- name: Install jenkins
  kubernetes.core.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    release_namespace: jenkins
    create_namespace: true