---
- name: Add prometheus helm repo
  kubernetes.core.helm_repository:
    name: prometheus
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Install prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus/prometheus
    release_namespace: prometheus
    create_namespace: true